blog/urls.py
from django.urls import path
# from blog.views import home, post_list, post_detail, post_create, post_update, post_delete,
from blog.views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = 'blog'

urlpatterns = [
    path('post-list/', PostListView.as_view(), name='post_list'),
    path('post-detail/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post-create/', PostCreateView.as_view(), name='post_create'),
    path('post-update/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
    path('post-delete/<int:pk>/', PostDeleteView.as_view(), name='post_delete'),
]

# path('', home),
#     path('post-create/', post_create, name='post_create'),
#     path('post-update/<int:post_id>/', post_update, name='post_update'),
#     path('post-delete/<int:post_id>/', post_delete, name='post_delete'),

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import urls as blog_urls
from custom_user import urls as custom_user_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(blog_urls, namespace='blog')),
    path('', include(custom_user_urls, namespace='custom_user')),
    path('tinymce/', include('tinymce.urls')),
]

custom_user/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from custom_user.views import UserCreateView, UserLoginView, UserProfileDetailView

app_name = 'custom_user'

urlpatterns = [
    path('signup/', UserCreateView.as_view(), name='signup'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/<int:pk>/', UserProfileDetailView.as_view(), name='profile')
]

blog/models.py
from django.db import models
from django.urls import reverse
from tinymce.models import HTMLField
from django.contrib.auth import get_user_model

User = get_user_model()


class Rating(models.Model):
    value = models.PositiveIntegerField(default=0)
    comment = models.CharField(max_length=200)

    def __str__(self):
        return str(self.value)


class Category(models.Model):
    NAME_CHOICES = (
        ('tech', 'Tech'),
        ('education', 'Education'),
        ('sports', 'Sports'),
        ('general', 'General')
    )
    name = models.CharField(max_length=20, choices=NAME_CHOICES, default='general')
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    STATUS_CHOICES = (
        ('active', 'Active'),
        ('deleted', 'Deleted'),
    )
    title = models.CharField(max_length=500, unique=True)
    body = HTMLField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='active')
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    rating = models.ForeignKey(Rating, on_delete=models.SET_NULL, null=True, blank=True)
    categories = models.ManyToManyField(Category, related_name='post_categories')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[str(self.id)])

    def __str__(self):
        return self.title[:70]

blog/forms.py
from django import forms
from blog.models import Post


# class PostCreateForm(forms.Form):
#     title = forms.CharField(max_length=500)
#     body = forms.CharField(widget=forms.Textarea, required=False)
#     status = forms.CharField(required=False)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = "__all__"
        exclude = ('author',)


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = "__all__"
        exclude = ('categories',)


# class PostUpdateForm(forms.Form):
#     title = forms.CharField(max_length=500, required=False)
#     body = forms.CharField(widget=forms.Textarea, required=False)
#     status = forms.CharField(required=False)

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin

from blog.models import Post
from blog.forms import PostUpdateForm, PostForm


def home(request, *args, **kwargs):
    return HttpResponse("This is Home Page")


def post_list(request, *args, **kwargs):
    posts = Post.objects.filter(status='active').order_by('id')
    response = {
        "posts": posts
    }
    return render(request, 'blog/post_list.html', response)


def post_detail(request, post_id, *args, **kwargs):
    post = Post.objects.get(id=post_id)
    response = {
        "post": post
    }
    return render(request, 'blog/post_detail.html', response)


# def post_create(request, *args, **kwargs):
#     empty_form = None
#     if request.method == 'POST':
#         data = request.POST
#         form_data = PostCreateForm(data=data)
#         if form_data.is_valid():
#             cl_data = form_data.cleaned_data
#             title = cl_data.get('title')
#             body = cl_data.get('body', None)
#             status = cl_data.get('status', 'active')
#             post = Post.objects.create(title=title, body=body, status=status)
#             return redirect('blog:post_detail', post_id=post.id)
#     else:
#         empty_form = PostCreateForm()
#     return render(request, 'blog/post_create.html', {'empty_form': empty_form})


def post_create(request, *args, **kwargs):
    empty_form = None
    if request.method == 'POST':
        data = request.POST
        form_data = PostForm(data=data)
        if form_data.is_valid():
            form_data.save()
            return redirect('blog:post_detail', post_id=form_data.instance.id)
        else:
            response = {
                'empty_form': empty_form,
                'error': form_data.errors if form_data.errors else None,
            }
            return render(request, 'blog/post_create.html', context=response)
    else:
        empty_form = PostForm()
    return render(request, 'blog/post_create.html', {'empty_form': empty_form})


# def post_update(request, post_id, *args, **kwargs):
#     empty_form = None
#     post_obj = Post.objects.get(id=post_id)
#     if request.method == 'POST':
#         data = request.POST
#         form_data = PostUpdateForm(data=data)
#         if form_data.is_valid():
#             cl_data = form_data.cleaned_data
#             if cl_data.get('title', None):
#                 post_obj.title = cl_data['title']
#                 post_obj.save()
#             if cl_data.get('body', None):
#                 post_obj.body = cl_data['body']
#                 post_obj.save()
#             if cl_data.get('status', None):
#                 post_obj.status = cl_data['status']
#                 post_obj.save()
#             return redirect('blog:post_detail', post_id=post_id)
#     else:
#         data = {
#             'title': post_obj.title,
#             'body': post_obj.body,
#             'status': post_obj.status
#         }
#         empty_form = PostUpdateForm(data=data)
#     return render(request, 'blog/post_create.html', {'empty_form': empty_form})


def post_update(request, post_id, *args, **kwargs):
    empty_form = None
    post_obj = Post.objects.get(id=post_id)
    if request.method == 'POST':
        data = request.POST
        form_data = PostUpdateForm(data=data, instance=post_obj)
        if form_data.is_valid():
            form_data.save()
            return redirect('blog:post_detail', post_id=post_id)
    else:
        empty_form = PostUpdateForm(instance=post_obj)
    return render(request, 'blog/post_create.html', {'empty_form': empty_form})


def post_delete(request, post_id, *args, **kwargs):
    Post.objects.get(id=post_id).delete()
    return redirect('blog:post_list')


# ---------------------------------class based View------------------

class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'blog/post_list.html'


class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/post_detail.html'


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(PostCreateView, self).form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(PostUpdateView, self).form_valid(form)

    def test_func(self):
        post_obj = self.get_object()
        if self.request.user == post_obj.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'blog/post_confirm_delete.html'
    success_url = reverse_lazy('blog:post_list')

    def test_func(self):
        post_obj = self.get_object()
        if self.request.user == post_obj.author:
            return True
        return False

blog/templates/blog/base.html
<!DOCTYPE html>
{% load custom_tags %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    <div class="container">
       <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            {% if user.is_authenticated %}
                {% get_profile_id user.id as profile_id %}
                <a class="nav-item nav-link active" href="{% url 'custom_user:profile' profile_id %}">Welcome {{ user.username }}!!!</a>
                <a class="nav-item nav-link active" href="{% url 'custom_user:logout' %}">Log out</a>


            {% else %}
                <a class="nav-item nav-link active" href="{% url 'custom_user:signup' %}">Sign Up</a>
                <a class="nav-item nav-link active" href="{% url 'custom_user:login' %}">Log in</a>
            {% endif %}
            <a class="nav-item nav-link active" href="{% url 'blog:post_list' %}">Home</a>
            <a class="nav-item nav-link active" href="{% url 'blog:post_create' %}">Create</a>
        </div>
      </div>
    </nav>
      <div class="row">
        <div class="col-sm">
          {% block content %}

          {% endblock %}
        </div>
      </div>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% block title %} Delete Post{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
  <input type="submit" value="Delete">
</form>
{% endblock %}

blog/templates/blog/post_create.html
{% extends 'blog/base.html' %}
{#{% load crispy_forms_filters %}#}
{% load crispy_forms_tags %}
{% block title %} Post Create{% endblock %}
{% block content %}
{#    {% if error %}#}
{#        <b> Some This went Wrong {{ error }}</b>#}
{#    {% endif %}#}
<form method="post">
    {% csrf_token %}
    {{ form.media }}
    {{ form|crispy }}
  <input type="submit" value="Submit">
</form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block title %} {{ post.title }} {% endblock %}
{% block content %}
    <div class="card">
      <h5 class="card-header">{{ post.title }} --{{ post.author }}</h5>
      <div class="card-body">
        <h5 class="card-title">Status: {{ post.status.capitalize }} | {{ post.created_at }}</h5>
        <p class="card-text">{{ post.body| safe }}</p>
          <a href="{% url 'blog:post_update' post.id %}" class="btn btn-primary">Edit This Post</a>
          <a href="{% url 'blog:post_delete' post.id %}" class="btn btn-primary">Delete This Post</a>
      </div>
    </div>
{% endblock %}

blog/templates/blog/post_list.html
{#{% extends 'blog/base.html' %}#}
{#{% block title %} Post List{% endblock %}#}
{#{% block content %}#}
{#    {% for post in posts %}#}
{#        <div class="post-container">#}
{#            <div class="title">#}
{#                <h3><a href=" {{post.get_absolute_url}} ">{{post.title}} </a></h3>#}
{#                <p>Published: {{post.created_at}} </p>#}
{#            </div>#}
{#            <p>{{post.post_body |slice:":50"}} </p>#}
{##}
{#            <div class="more-btn">#}
{#                <a href="{{post.get_absolute_url}}">Read More</a>#}
{#            </div>#}
{#        </div>#}
{#    {% endfor %}#}
{##}
{#{% endblock %}#}
{##}

{% extends 'blog/base.html' %}
{% block title %} Post List{% endblock %}
{% block content %}
    {% for post in posts %}
            <div class="card">
      <h5 class="card-header">{{ post.title }}</h5>
      <div class="card-body">
        <h5 class="card-title">Status: {{ post.status.capitalize }} | {{ post.created_at }}</h5>
        <p class="card-text">{{ post.body|truncatechars:100 }}</p>
        <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">Show More</a>
      </div>
    </div>
    {% endfor %}
{% endblock %}